stages: 
  - test 
  - deploy 
test-job: 
  stage: test 
  script: 
    - echo "Running tests..." 
    - python -m unittest discover -s hello-devops 
deploy-job: 
  stage: deploy 
  script: 
    - echo "Deploying application..." 
